### ISSUE TITLE
Face recognition not working if object recognition is installed too

### ISSUE THREAD

**Issue by danhajduk** [robmarkcole/HASS-Deepstack-face#49]
I have installed both the object and face recognition.
When I try to run face recognition on the deepstack log I see `/v1/vision/detection.`
this is my configuration for the face recognition
```
  - platform: deepstack_face
    ip_address: 192.168.1.200
    port: 80
    api_key: !secret deepstack_api_key
    timeout: 5
    detect_only: False
    save_file_folder: /config/www/snapshots/
    save_timestamped_file: False
    save_faces: True
    save_faces_folder: /config/www/faces/
    show_boxes: True
    source:
      - entity_id: camera.camera_11
        name: face_counter
```
