### ISSUE TITLE
image_processing.scan results in "Unable to find referenced entities"

### ISSUE THREAD

**Issue by steemsjo** [robmarkcole/HASS-Deepstack-face#53]
Following the tutorials of Everything Smart Home.
Got to the point I set up the automation to start deepstack with the image of the camera.

For testing purpose I set up a local camera in hass:
``` yml
camera:
  - platform: local_file
    name: test_local_file_face
    file_path: /media/frigate/clips/yoosee_frigate-1630426277.427424-9ztudw.jpg
```
This is just a random detected person image frame of me.

And invoking the service as follows:
``` yml
service: image_processing.scan
target:
  entity_id: camera.test_local_file_face
```

And the result in the log is:
> WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.test_local_file_face

Looking at the Deepstack output, it also does not show any movement of some sort.
Using something like deepstack-ui or deepstack trainer, shows activity with status code 200. I taught it ~187 images of faces already without any problem. Also deepstack-ui returns the proper person being detected when I manually scan a image of a taught person.

Is the problem within the custom_component or is it with the image I'm using?
Currently using `deepquestai/deepstack:cpu-x5-beta` as others failed to work properly (giving 500's).

**Comment by robmarkcole** [comment]
Well this is your error, please correct: `Unable to find referenced entities camera.test_local_file_face`

**Comment by Rbillon59** [comment]
Hi,

Got the exact same error. I've added the camera from MotionEye integration and the deepstack face from hacs :

```yaml
image_processing:
  - platform: deepstack_face
    ip_address: ipaddress
    port: 80
    #api_key: mysecretkey
    timeout: 5
    detect_only: False
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
    save_faces: True
    save_faces_folder: /config/faces/
    show_boxes: True
    source:
      - entity_id: camera.entree
        name: camera_entree
```

The camera is working properly and the entity as well but got :

```sh
Logger: homeassistant.helpers.service
Source: helpers/service.py:128
First occurred: 12:25:54 (4 occurrences)
Last logged: 12:37:00

Unable to find referenced entities camera.entree
```

while calling : 

```yaml
service: image_processing.scan
target:
  entity_id: camera.entree
```

**Comment by robmarkcole** [comment]
You can check all the entities in the home assistant UI, this should be there?

**Comment by steemsjo** [comment]
> the entity is definitely there then, so sounds like a legit bug on home assistant side

I'm not necessarily convinced about this. Searching for the exact message `"Unable to find referenced entities"` on [Google](https://www.google.com/search?hl=en&q=%22Unable%20to%20find%20referenced%20entities%22) gives a wild range of people with this message, going from automations to custom components but also typos. So it's strange. I want to pinpoint it.

**Comment by Rbillon59** [comment]
Hi, just updated my home assistant to core-2021.9.3, the warning is gone and the service is working properly. I can see requests in the deepstack server logs.

@steemsjo would you give a try after updating ?

**Comment by steemsjo** [comment]
@Rbillon59 I also updated and saw 200's coming by in the deepstack log. The strange thing however is the fact I can only pick 1 entity to send to the service call, which is:
``` yml
service: image_processing.scan
target:
  entity_id: image_processing.frigate_front_door
```
While before I could select a whole list of different kind of entities. 
Also manually triggering the service results in `HTTP 400 BAD REQUEST` . So something is still wrong here?
