### ISSUE TITLE
Training event not firing.

### ISSUE THREAD

**Issue by bobsiboo** [robmarkcole/HASS-Deepstack-face#64]
Hi,

I am running deepstack on my truenas core server in a docker container.
my Home assistant seems to make a propper connection, i get immages in my folders with faces labeled as unknown and boxes trown arround them as advertised. 

however, the one thing i can't get to work is training any faces.
It looks like the event deepstack_face.teach_face is not firing ever.

when I listen for this event and then proceed to train the model no events are found.
I scan the logs of my docker and nothing appears.

I am not sure what i have done wrong. 

Curent config:
```
image_processing:
  - platform: deepstack_face
    ip_address: 10.2.69.20
    port: 10049
    detect_only: False
    timeout: 30
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
    save_faces: True
    save_faces_folder: /config/faces/
    show_boxes: True
    source:
      - entity_id: camera.voordeur_high
        name: face_counter
```
