### ISSUE TITLE
 Face endpoints not activated

### ISSUE THREAD

**Issue by kuradi** [robmarkcole/HASS-Deepstack-face#9]
i have object working good, but face giving me error in homeassistant:
[custom_components.deepstack_face.image_processing] Depstack error : Error from Deepstack: Face endpoints not activated

```
  - platform: deepstack_face
    ip_address: ***.***.*.***
    port: 85
    api_key: /key/
    timeout: 30
    detect_only: False
    scan_interval: 20
    source:
      - entity_id: camera.hoov
        name: face_counter_hoov
```
where and how should activate endpoint?
